swagger: '2.0'
info:
  description: "Upload the LSTM model file"
  version: "1.0.0"
  title: "Upload LSTM Model"
paths:
  /upload_lstm:
    post:
      tags:
        - "model"
      summary: "Upload LSTM model"
      description: "Upload the LSTM model file"
      consumes:
        - "multipart/form-data"
      produces:
        - "application/json"
      parameters:
        - name: "file"
          in: "formData"
          description: "The LSTM model file to upload"
          required: true
          type: "file"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
